#########
## client
#########
client:
  pk: id
  fields:
    id: INT NOT NULL AUTO_INCREMENT
    user_id: INT
    type: TINYINT
    name: VARCHAR(24) NOT NULL
    dob: INT
    xueli: TINYINT
    yasichengji: VARCHAR(3)
    dianhua: VARCHAR(20)
    dizhi: VARCHAR(512)
    email: VARCHAR(36)
    keyuan: VARCHAR(36)
    beizhu: TEXT
    created_at: INT
  fks:
    user_id:
      foreign_key: user_id
      references: site_user.id
      on_delete: SET NULL
      on_update: SET NULL
  form:
    fields:
      user_id:
        widget: select
        widget_conf:
          required: 1
          options:
            1: 职员1
            2: 职员2
            3: 职员3
      type:
        widget: select
        widget_conf:
          required: 0
          options:
            1: 留学
            2: 移民
      name:
        widget: text
        widget_conf:
          required: 1
      dob:
        widget: datepicker
        widget_conf:
          required: 0
          format: yy/mm/dd
          
      chushengriqi:
        widget: text
        widget_conf:
          required: 0
      xueli:
        widget: select
        widget_conf:
          required: 0
          options:
            0: -- 请选择 --
            初中: 初中
            高中: 高中
            大专: 大专
            本科: 大学
            研究生: 研究生
      yasichengji:
        widget: select
        widget_conf:
          required: 0
          options:
            0: -- 请选择 --
            3: 3
            3.5: 3.5
            4: 4
            4.5: 4.5
            5: 5
            5.5: 5.5
            6: 6
            6.5: 6.5
            7: 7
            7.5: 7.5
            8: 8
            8.5: 8.5
            9: 9
      dianhua:
        widget: text
        widget_conf:
          required: 1
      dizhi:
        widget: textarea
        widget_conf:
          required: 1
      email:
        widget: email
        widget_conf:
          required: 1
          size: 30
      keyuan:
        widget: select
        widget_conf:
          required: 0
          options:
            0: -- 请选择 --
            熟人推荐: 熟人推荐
            国内中介: 国内中介
            网络: 网络
            广告宣传: 广告宣传
      beizhu:
        widget: textarea
        widget_conf:
          required: 0
    names:
      en: Client
      zh: 客户
      
document:
  pk: id
  fields:
    id: INT NOT NULL AUTO_INCREMENT
    client_id: INT
    type: VARCHAR(4)
    name: VARCHAR(255)
    uri: VARCHAR(255)
  fks:
    client_id:
      foreign_key: client_id
      references: client.id
      on_delete: CASCADE
      on_update: CASCADE

###############
### Institution
###############
#institution:
#  pk: id
#  fields:
#    id: INT NOT NULL AUTO_INCREMENT
#    name: VARCHAR(256) NOT NULL
#    commission_rate: FLOAT(2,2)
#
##########
### Course
##########
#course:
#  pk: id
#  fields:
#    id: INT NOT NULL AUTO_INCREMENT
#    user_id: INT
#    institution_id: INT
#    stage: VARCHAR(128)
#    name: VARCHAR(256) NOT NULL
#    commission_rate: FLOAT(2,2)
    