routing:
  index:
    path: ^\/?$
    isSecure: 0
    i18n: 0
    controller: site/index


assets:
  frontend:
    css:
      # bootstrap
      bootstrap:
        path: .?
        position: top
        weight: 10
        source: //maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css
      # sweet_alert
      sweet_alert:
        path: .?
        position: top
        weight: 20
        source: site/assets/bootstrap-sweetalert/lib/sweet-alert.css
      # fontawesome
      fontawesome:
        path: .?
        position: top
        weight: 30
        source: //maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css
      # animate
        path: .?
        position: top
        weight: 40
        source: ../../original_theme/css/animate.css
      # original
        path: .?
        position: top
        weight: 50
        source: ../../original_theme/css/style.css
      # site
      site:
        path: .?
        position: top
        weight: 40
        source: site/assets/css/style.css
        
    js:
      bootstrap:
        path: .?
        position: bottom
        weight: 10
        source: //netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js
      sweet_alert:
        path: .?
        position: top
        weight: 30
        source: site/assets/bootstrap-sweetalert/lib/sweet-alert.min.js


#        source: site/assets/js/bootstrap.min.js
#      swiper:
#        path: .?
#        position: bottom
#        weight: 20
##        source: https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.x.x/js/swiper.jquery.min.js
#        source: site/assets/js/swipe.jquery.min.js
      site:
        path: .?
        position: bottom
        weight: 30
        source: site/assets/js/script.js
