routing:
  index:
    path: ^\/?$
    isSecure: 0
    i18n: 0
    controller: site/index
  profile:
    path: ^\/profile\/?$
    isSecure: 0
    i18n: 0
    controller: site/profile
  siteuser_list:
    path: ^\/siteuser\/list\/?$
    isSecure: 0
    i18n: 0
    controller: site/siteuser_list
  siteuser_edit:
    path: ^\/siteuser\/edit\/(\d+)\/?$
    isSecure: 0
    i18n: 0
    controller: site/siteuser_edit
  siteuser_delete:
    path: ^\/siteuser\/delete\/(\d+)\/?$
    isSecure: 0
    i18n: 0
    controller: site/siteuser_delete
  siteuser_create:
    path: ^\/siteuser\/add\/?$
    isSecure: 0
    i18n: 0
    controller: site/siteuser_add
  client_list:
    path: ^\/client\/list\/?$
    isSecure: 0
    i18n: 0
    controller: site/client_list
  client_add:
    path: ^\/client\/add\/?$
    isSecure: 0
    i18n: 0
    controller: site/client_add
  client_edit:
    path: ^\/client\/edit\/(\d+)\/?$
    isSecure: 0
    i18n: 0
    controller: site/client_edit
  client_details:
    path: ^\/client\/details\/(\d+)\/?$
    isSecure: 0
    i18n: 0
    controller: site/client_details
    


assets:
  frontend:
    css:
      # bootstrap
      bootstrap:
        path: .?
        position: top
        weight: 10
        source: //maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css
      # sweet_alert
      sweet_alert:
        path: .?
        position: top
        weight: 20
        source: ../../original_theme/css/plugins/sweetalert/sweetalert.css
      # font-awesome
      fontawesome:
        path: .?
        position: top
        weight: 30
        source: ../../original_theme/font-awesome/css/font-awesome.css
      # original
      original:
        path: .?
        position: top
        weight: 50
        source: ../../original_theme/css/style.css
      # site
      site:
        path: .?
        position: top
        weight: 60
        source: site/assets/css/style.css
        
    js:
      bootstrap:
        path: .?
        position: bottom
        weight: 10
        source: //netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js
      sweet_alert:
        path: .?
        position: bottom
        weight: 30
        source: ../../original_theme/js/plugins/sweetalert/sweetalert.min.js
      metisMenu:
        path: .?
        position: bottom
        weight: 30
        source: ../../original_theme/js/plugins/metisMenu/jquery.metisMenu.js
      slimScroll:
        path: .?
        position: bottom
        weight: 30
        source: ../../original_theme/js/plugins/slimscroll/jquery.slimscroll.min.js
      
      original:
        path: .?
        position: bottom
        weight: 30
        source: ../../original_theme/js/inspinia.js
      site:
        path: .?
        position: bottom
        weight: 30
        source: site/assets/js/script.js
