routing:

  admin_company_list:
    path: ^\/admin\/company\/list\/?$
    isSecure: 1
    i18n: 1
    controller: company/backend/company_list
  admin_company_edit:
    path: ^\/admin\/company\/edit\/(\d+)\/?$
    isSecure: 1
    i18n: 1
    controller: company/backend/company_edit
  admin_company_create:
    path: ^\/admin\/company\/create\/?$
    isSecure: 1
    i18n: 1
    controller: company/backend/company_create
  admin_company_delete:
    path: ^\/admin\/company\/delete\/(\d+)\/?$
    isSecure: 1
    i18n: 0
    controller: company/backend/company_delete